### ISSUE TITLE
How to set the production branch

### ISSUE THREAD

**Issue by christian-schab** [coasy/terraform-provider-vercel#4]
I haven't found a way to set the production branch on a project.
It should be part of the git_repository object.

I would expect that this works:
```
resource "vercel_project" "project" {
  name = var.NAME
  git_repository {
    type             = "github"
    repo             = "coasy/${var.REPO}"
    production_branch = "master"
  }
```

But I get 

> Error: Unsupported argument
> 
>   on modules/components/vercel/project/main.tf line 15, in resource "vercel_project" "project":
>   15:     production_branch = "master"
> 
> An argument named "production_branch" is not expected here.

**Comment by suhodolskiy** [comment]
@christian-schab Hi! Please check next "branch" field. https://github.com/coasy/terraform-provider-vercel/blob/release/internal/provider/resource_project.go#L60

Example:
```
resource "vercel_project" "project" {
  name = var.NAME
  
  git_repository {
    type             = "github"
    repo             = "coasy/${var.REPO}"
  }

  branch = $BRANCH_NAME                <- production branch
  ...
}
```

**Comment by christian-schab** [comment]
@suhodolskiy Ah, I see. It is not part of git_repository but on parent object "project".

Thanks for clarifying!
